import { getAzurePatFromKeychain } from "./credentials.mjs";
import { ghApi, inPeriod } from "./utils.mjs";

const BOT = /\[bot\]|github-actions|dependabot|renovate/i;
const DEMO_DESC =
  /generated by demofabrikk|pitch demo|design-bakeoff|demofabrikk/i;
const DEMO_AUTHOR = /demo web|demofabrikk/i;

export function isDemofabrikkRepo(repo) {
  const name = String(repo.name ?? "").toLowerCase();
  const fullName = String(repo.fullName ?? "").toLowerCase();
  const desc = repo.description ?? "";

  if (/^demofabrikk(-|$)/.test(name)) return true;
  if (/^demo(-|$)/.test(name)) return true;
  if (/(^|\/)demo[-_/]/.test(fullName)) return true;

  if (DEMO_DESC.test(desc)) return true;

  const who = `${repo.author ?? ""} ${repo.authorLogin ?? ""}`.toLowerCase();
  if (DEMO_AUTHOR.test(who)) return true;

  // Namnlösa numrerade repos (typ caiacosmetics-6) från demo-pipelinen
  if (!desc.trim() && /-\d+$/.test(name)) return true;

  return false;
}

function recountAuthors(repos) {
  const byAuthor = new Map();
  for (const row of repos) {
    if (!row.author) continue;
    byAuthor.set(row.author, (byAuthor.get(row.author) ?? 0) + 1);
  }
  return byAuthor;
}

function humanAuthor(commit) {
  const login = commit?.author?.login ?? commit?.commit?.author?.name;
  if (!login || BOT.test(login)) return null;
  return login;
}

async function azureFetch(path, pat, org) {
  const auth = Buffer.from(`:${pat}`).toString("base64");
  const url = path.startsWith("http")
    ? path
    : `https://dev.azure.com/${org}/${path}`;
  const res = await fetch(url, {
    headers: { Authorization: `Basic ${auth}`, Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`Azure ${res.status}`);
  return res.json();
}

function firstCommitAuthor(fullName) {
  try {
    const commits = ghApi(`repos/${fullName}/commits?per_page=8`);
    for (const c of commits) {
      const login = humanAuthor(c);
      if (login) return login;
    }
  } catch {
    /* skip */
  }
  return null;
}

export async function fetchNewProjects(config, { from, to }, fmtName) {
  const org = config.org;
  const result = {
    status: "pending",
    repos: [],
    byAuthor: new Map(),
    githubCount: 0,
    azureCount: 0,
  };

  try {
    let page = 1;
    const ghRepos = [];
    while (page <= 3) {
      const data = ghApi(
        `search/repositories?q=org:${org}+created:>=${from}&sort=created&order=asc&per_page=100&page=${page}`
      );
      const items = data.items ?? [];
      ghRepos.push(...items);
      if (items.length < 100) break;
      page++;
    }

    const inPeriodRepos = ghRepos.filter((repo) =>
      inPeriod(repo.created_at?.slice(0, 10), from, to)
    );
    console.log(`  Nya GitHub-repos (${inPeriodRepos.length})…`);

    const realGhRepos = inPeriodRepos.filter(
      (repo) =>
        !isDemofabrikkRepo({
          name: repo.name,
          fullName: repo.full_name,
          description: repo.description ?? "",
        })
    );

    for (const repo of realGhRepos) {
      result.repos.push({
        name: repo.name,
        fullName: repo.full_name,
        source: "github",
        created: repo.created_at?.slice(0, 10),
        description: repo.description ?? "",
        author: null,
        authorLogin: null,
      });
    }

    for (const entry of realGhRepos.slice(0, 20)) {
      const author = firstCommitAuthor(entry.full_name);
      if (!author) continue;
      const named = fmtName(author);
      const row = result.repos.find((r) => r.fullName === entry.full_name);
      if (row) {
        row.author = named;
        row.authorLogin = author;
      }
      result.byAuthor.set(named, (result.byAuthor.get(named) ?? 0) + 1);
    }
    result.repos = result.repos.filter((r) => !isDemofabrikkRepo(r));
    result.byAuthor = recountAuthors(result.repos);
    result.githubCount = result.repos.filter((r) => r.source === "github").length;
  } catch (e) {
    result.githubError = String(e.message ?? e);
  }

  const pat = getAzurePatFromKeychain();
  const azOrg = config.azure?.org ?? "thirdact";
  if (pat) {
    try {
      const { value: projects = [] } = await azureFetch(
        `_apis/projects?api-version=7.1&$top=100`,
        pat,
        azOrg
      );
      for (const project of projects) {
        const proj = project.name;
        try {
          const { value: repos = [] } = await azureFetch(
            `${encodeURIComponent(proj)}/_apis/git/repositories?api-version=7.1`,
            pat,
            azOrg
          );
          for (const repo of repos) {
            const created = repo.creationDate?.slice(0, 10);
            if (!inPeriod(created, from, to)) continue;
            result.repos.push({
              name: repo.name,
              fullName: `${proj}/${repo.name}`,
              source: "azure",
              created,
              author: null,
              project: proj,
            });
          }
        } catch {
          /* skip project */
        }
      }
      result.azureCount = result.repos.filter((r) => r.source === "azure").length;
    } catch (e) {
      result.azureError = String(e.message ?? e);
    }
  }

  result.repos = result.repos.filter((r) => !isDemofabrikkRepo(r));
  result.byAuthor = recountAuthors(result.repos);
  result.githubCount = result.repos.filter((r) => r.source === "github").length;
  result.azureCount = result.repos.filter((r) => r.source === "azure").length;
  result.status = result.repos.length ? "ok" : "empty";
  result.total = result.repos.length;
  return result;
}
